create table
  public.potions (
    "SKU" text not null,
    name text null,
    red integer null,
    green integer null,
    blue integer null,
    dark integer null,
    quantity integer null,
    price integer null,
    constraint potions_pkey primary key ("SKU"),
    constraint potions_SKU_key unique ("SKU")
  ) tablespace pg_default;

create table
  public.carts (
    cart_id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_id integer null,
    constraint carts_pkey primary key (cart_id),
    constraint public_carts_customer_id_fkey foreign key (customer_id) references customers (customer_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer generated by default as identity,
    "SKU" text not null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (cart_id, "SKU"),
    constraint public_cart_items_SKU_fkey foreign key ("SKU") references potions ("SKU"),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id)
  ) tablespace pg_default;

create table
  public.customers (
    customer_id integer generated by default as identity,
    name text null,
    created_at timestamp with time zone null,
    constraint customers_pkey primary key (customer_id)
  ) tablespace pg_default;